# See: https://docs.conda.io/projects/conda-build/en/latest/resources/build-scripts.html
# See: https://docs.ligo.org/lscsoft/conda/packaging/

package:
  name: vczip
  version: v1.0.0

source:
  url: https://github.com/divonlan/vczip/archive/v1.0.0.tar.gz
  sha256: 29449b5869b1e9fb72e13184ae3f43739f1e5e711d10f2bd365332e55650b6d1

build:
  number: 0

requirements:
  build:
    # If your project compiles code (such as a C extension) then add the required compilers as separate entries here.
    # Compilers are named 'c', 'cxx' and 'fortran'.
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python

test:
  # Some packages might need a `test/commands` key to check CLI.
  # List all the packages/modules that `run_test.py` imports.
  imports:
    - simplejson
    - simplejson.tests

about:
  home: https://github.com/divonlan/vczip
  # Remember to specify the license variants for BSD, Apache, GPL, and LGPL.
  # Prefer the short version, e.g: GPL-2.0 instead of GNU General Public License version 2.0
  # See https://opensource.org/licenses/alphabetical
  license: Apache-2.0, non-commercial only
  license_family: Apache

  license_file: LICENSE.non-commercial.txt
  summary: 'Compressor for VCF genomic files, a lot better than gzip or bzip2'

  description: |
    vczip is a compressor for VCF genomic files (it compresses .vcf or .vcf.gz files). 
    It is very easy to use - in fact, if you're familiar with gzip, it works pretty much the same.
    It achieves x2 to x5 better compression ratios than gzip because it leverages some properties
    of the genomic data, such as linkage disequilibrium, to compress better. 
    It is also a lot faster than gzip. 
    The compression is lossless - the decompressed file is identical to the original file.
  doc_url: https://vczip.readthedocs.io/
  dev_url: https://github.com/divonlan/vczip

extra:
  recipe-maintainers:
    - divonlan
