
package:
  name: vczip
  version: 1.0.0

source:
  url: https://github.com/divonlan/vczip/archive/vczip-1.0.0.tar.gz
  sha256: 705894eeb19f2668fdc469de827e22e67716b7c97ccfded30cbd136539b12759

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
  run:

test:
  files: 
    - data/test-file.vcf

  commands:
    - test -f $PREFIX/vczip         # [unix]
    - vczip -t test-file.vcf        # [unix]
    - if not exist $PREFIX/vczip.exe exit 1  # [win]
    - .\vczip.exe -t test-file.vcf  # [win]

about:
  home: https://github.com/divonlan/vczip
  dev_url: https://github.com/divonlan/vczip
  license: Apache-2.0, non-commercial only
  license_family: Apache
  license_file: LICENSE.non-commercial.txt
  summary: 'Compressor for VCF genomic files, a lot better than gzip or bzip2'
  description: |
    vczip is a compressor for VCF genomic files (it compresses .vcf or .vcf.gz files). 
    It is very easy to use - in fact, if you're familiar with gzip, it works pretty much the same.
    It achieves x2 to x5 better compression ratios than gzip because it leverages some properties
    of the genomic data, such as linkage disequilibrium, to compress better. 
    It is also a lot faster than gzip. 
    The compression is lossless - the decompressed file is identical to the original file.

extra:
  recipe-maintainers:
    - divonlan
