
package:
  name: vczip
  version: 1.0.0

source:
  url: https://github.com/divonlan/vczip/archive/vczip-1.0.0.tar.gz
  sha256: ea60357f843abdd74c13efa739984f52b620a56b8c2c48567b6ce1b16adc4762

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
  run:

test:
  files: 
    - data/test-file.vcf

  commands:
    - vczip -t test-file.vcf        # [unix]
    - .\vczip.exe -t test-file.vcf  # [win]

about:
  home: https://github.com/divonlan/vczip
  dev_url: https://github.com/divonlan/vczip
  license: Apache-2.0, non-commercial only
  license_family: Apache
  license_file: LICENSE.non-commercial.txt
  summary: 'Compressor for VCF genomic files, a lot better than gzip or bzip2'
  description: |
    vczip is a compressor for VCF genomic files (it compresses .vcf or .vcf.gz files). 
    It is very easy to use - in fact, if you're familiar with gzip, it works pretty much the same.
    It achieves x2 to x5 better compression ratios than gzip because it leverages some properties
    of the genomic data, such as linkage disequilibrium, to compress better. 
    It is also a lot faster than gzip. 
    The compression is lossless - the decompressed file is identical to the original file.

extra:
  recipe-maintainers:
    - divonlan
